### ISSUE TITLE
Trouble connecting with Bluetooth

### ISSUE THREAD

**Issue by aerickt** [Anodynous/stenogotchi#1]
I'm trying to set up a Stenogotchi, and I've been having an issue with Bluetooth.

If I attempt to connect to my device from the Stenogotchi with Bluetoothctl, it simply fails with `Failed to connect: org.bluez.Error.Failed`. Here is a pastebin of what I try with bluetoothctl: <https://pastebin.com/frikJp1m>

If I try to connect to the Stenogotchi from my device, it connects momentarily, but it disconnects two seconds afterwards. I get the following errors when I run `systemctl status bluetooth`.

```
Sap driver initialization failed.
sap-server: Operation not permitted (1)
Failed to set privacy: Rejected (0x0b)
a2dp-sink profile connect failed for <device id>: Protocol not available
a2dp-source profile connect failed for <device id>: Protocol not available
```

Furthermore, the Stenogotchi does not seem to be discoverable on boot up. I have to use `bluetoothctl` to set discoverable to on and to be able to see it on my devices.

I'm not sure what's going on since I'm pretty certain I've followed the instructions correctly. This is the fourth time I've set it up from a fresh installation of dietpi.

I should also mention that I'm only using the RPi0W by itself and without any of the recommended hardware. But I don't *think* that's relevant to my issue.

Appreciate any help, thanks.

**Comment by aerickt** [comment]
I just figured out that not having a waveshare e-ink display *was* related to my issue... Sort of. I need to enable the SPI interface otherwise `stenogotchi.py` wouldn't run at all even though no errors were outputted to `/var/log/stenogotchi.log`.

The last two errors in the above post are related to Bluetooth audio which is really odd but I couldn't figure out how to disable those on my Bluetooth client. I use blueman, and it seems it wants to enable both HID and audio protocols for some reason and I've not been able to figure out how to disable a2dp. So instead, I ended up just installing the pulseaudio Bluetooth module on the Stenogotchi. And that makes the a2dp related errors go away, in addition to letting my device connect to the Stenogotchi.

However despite this, I'm still not getting intended behaviour. Any key press on my steno machine will not output onto the connected device. And when the Stenogotchi first connects, it starts spamming the C key so I get `CCCCCCCCCCCC...` in whatever text field I'm focused on. This is the output of `/var/log/stenogotchi.log`:

```
[2021-07-26 10:38:33,258] [INFO] [plover_link] Waiting for connections
[2021-07-26 10:41:24,676] [INFO] [plover_link] <device id> connected on the control socket
[2021-07-26 10:41:24,708] [INFO] [plover_link] <device id> connected on the interrupt channel
[2021-07-26 10:41:25,230] [INFO] [plover_link] Device <device name> [<device id>] is connected
[2021-07-26 10:41:25,339] [ERROR] Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
TypeError: interfaces_added() takes 1 positional argument but 3 were given
[2021-07-26 10:41:25,409] [ERROR] Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
TypeError: interfaces_added() takes 1 positional argument but 3 were given
[2021-07-26 10:41:25,430] [ERROR] Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 232, in maybe_handle_message
    self._handler(*args, **kwargs)
TypeError: interfaces_added() takes 1 positional argument but 3 were given
[2021-07-26 10:41:25,451] [DEBUG] [plover_link] plover_is_running = 1
[2021-07-26 10:41:25,624] [INFO] [plover_link] The client has been disconnected
[2021-07-26 10:41:25,768] [INFO] [plover_link] No bt_autoconnect_mac set in config. Listening for incoming connections instead...
[2021-07-26 10:41:25,776] [INFO] [plover_link] Waiting for connections
[2021-07-26 10:43:10,919] [INFO] [plover_link] <device id> connected on the control socket
[2021-07-26 10:43:10,952] [INFO] [plover_link] <device id> connected on the interrupt channel
[2021-07-26 10:43:11,047] [INFO] [plover_link] Device <device name> [<device id>] is connected
[2021-07-26 10:43:11,128] [DEBUG] [plover_link] plover_is_ready = 1
[2021-07-26 10:43:11,282] [DEBUG] [plover_link] plover_machine_state = machine_type: Gemini PR machine_state: connected
[2021-07-26 10:43:11,348] [INFO] [plover_link] The client has been disconnected
[2021-07-26 10:43:11,482] [INFO] [plover_link] No bt_autoconnect_mac set in config. Listening for incoming connections instead...
[2021-07-26 10:43:11,484] [INFO] [plover_link] Waiting for connections
[2021-07-26 10:44:25,166] [INFO] [plover_link] <device id> connected on the control socket
[2021-07-26 10:44:25,201] [INFO] [plover_link] <device id> connected on the interrupt channel
[2021-07-26 10:44:25,299] [INFO] [plover_link] Device <device name> [<device id>] is connected
[2021-07-26 10:44:25,406] [INFO] [plover_link] The client has been disconnected
[2021-07-26 10:44:25,568] [INFO] [plover_link] No bt_autoconnect_mac set in config. Listening for incoming connections instead...
```

**Comment by aerickt** [comment]
`plover.log` is also filled with these errors:
```
2021-07-26 10:56:57,393 [Thread-1-engine] ERROR: hook 'send_string' callback <bound method EngineServer._on_send_string of <stenogotchi_link.stenogotchi_link.EngineServer object at 0xb32e86f0>> failed
Traceback (most recent call last):
  File "/root/plover/plover/engine.py", line 535, in _trigger_hook
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/stenogotchi_link/stenogotchi_link.py", line 171, in _on_send_string
    self._btclient.send_string(text)
  File "/usr/local/lib/python3.7/dist-packages/stenogotchi_link/clients.py", line 209, in send_string
    mapping.modifiers)
  File "/usr/local/lib/python3.7/dist-packages/stenogotchi_link/clients.py", line 184, in send_plover_keycode
    self.send_keys()
  File "/usr/local/lib/python3.7/dist-packages/stenogotchi_link/clients.py", line 155, in send_keys
    self.btk_service.send_keys(self.state)
  File "/usr/local/lib/python3.7/dist-packages/dbus/proxies.py", line 147, in __call__
    **keywords)
  File "/usr/local/lib/python3.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```

**Comment by aerickt** [comment]
Simple reboot as well as pairing/unpairing with bluetoothctl seems to have fixed it. Strokes are output correctly as intended. I would like to see if there's a better way to fix the original a2dp problem, but closing for now.
