### ISSUE TITLE
Can't reach the web UI

### ISSUE THREAD

**Issue by rmulligan** [Anodynous/stenogotchi#4]
I'm seeing the following message in the debug log and though it says the ui is available I am unable to reach it, and using 'lsof -i :8080 am not seeing anything running on the port.

Any suggestions?

2021-10-07 01:45:43,221] [INFO] web ui available at http://192.168.86.58:8080/
Exception ignored in thread started by: <bound method Server._http_serve of <stenogotchi.ui.web.server.Server object at 0xb4375ca0>>
Traceback (most recent call last):
  File "/root/stenogotchi/stenogotchi/ui/web/server.py", line 49, in _http_serve
    app.run(host=self._address, port=self._port, debug=False)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 922, in run
    run_simple(t.cast(str, host), port, self, **options)

**Comment by Anodynous** [comment]
This bug has been fixed with e1dee3b2f618d89520114c694a2f08f11f3d93f0
